### PR TITLE
feat: add base helm chart

### PR DESCRIPTION
**Pull request by M0NsTeRRR**
I've moved everything to this new repository and I've added on top :
 - https://github.com/Stirling-Tools/Stirling-PDF/pull/2178
 - https://github.com/Stirling-Tools/Stirling-PDF/pull/2174

As before we have to setup gh-pages branch as described here : https://github.com/Stirling-Tools/Stirling-PDF/pull/2113

Regression : The sync script can't be moved for now as it reads the gradle file.

Do you want to setup a DNS entry for the github  page ? otherwise it would be `https://stirling-tools.github.io/Stirling-PDF-chart`

@Frooodle

### CODE REVIEW

**Comment by Frooodle** [comment]
https://stirling-tools.github.io/Stirling-PDF-chart 
Should be fine, its what most would expect I guess

and thanks again for this, awesome work

**Comment by Frooodle** [comment]
gh-pages pushed

**Comment by Frooodle** [comment]
ahh seems its pushed to 
http://docs.stirlingpdf.com/Stirling-PDF-chart/

**Comment by M0NsTeRRR** [comment]
Ah yes I think it's because the name is on the organization ? which one would you want to keep ?

**Comment by M0NsTeRRR** [comment]
Can you also pin the github pages address in the `About` ?
image

**Pull request merged**
